name: Build Docker Container

on:
  push:
    branches:
      - self
jobs:
  docker-build-and-push:
    runs-on: self-hosted
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bjjware/githubaction-hello-world:latest
  my-job:
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: my-step
        run: echo "Hello World!"
    
